package migration

import (
	"fmt"
	"strings"
)

type createTableSQL struct {
	Statements []string
}

func generateCreateTableSQL(mi modelInfo) createTableSQL {
	cols := make([]string, 0, len(mi.Fields))
	idxs := []string{}
	var pk string
	for _, f := range mi.Fields {
		col := fmt.Sprintf("%s %s", f.DBName, normalizeType(f))
		if f.NotNull {
			col += " NOT NULL"
		}
		if f.Default != "" {
			col += " DEFAULT " + f.Default
		}
		if f.AutoInc {
			col += " GENERATED BY DEFAULT AS IDENTITY"
		}
		cols = append(cols, col)
		if f.PrimaryKey {
			pk = f.DBName
		}
		if f.Unique {
			idxs = append(idxs, fmt.Sprintf("CREATE UNIQUE INDEX IF NOT EXISTS idx_%s_%s ON %s(%s)", mi.TableName, f.DBName, mi.TableName, f.DBName))
		}
		if f.Index && !f.Unique {
			idxs = append(idxs, fmt.Sprintf("CREATE INDEX IF NOT EXISTS idx_%s_%s ON %s(%s)", mi.TableName, f.DBName, mi.TableName, f.DBName))
		}
		// foreign key constraints
		if f.FKTable != "" && f.FKColumn != "" {
			idxs = append(idxs, fmt.Sprintf("ALTER TABLE %s ADD CONSTRAINT IF NOT EXISTS fk_%s_%s FOREIGN KEY (%s) REFERENCES %s(%s)", mi.TableName, mi.TableName, f.DBName, f.DBName, f.FKTable, f.FKColumn))
		}
	}
	if pk != "" {
		cols = append(cols, fmt.Sprintf("PRIMARY KEY (%s)", pk))
	}
	sb := strings.Builder{}
	sb.WriteString("CREATE TABLE IF NOT EXISTS ")
	sb.WriteString(mi.TableName)
	sb.WriteString(" (")
	sb.WriteString(strings.Join(cols, ", "))
	sb.WriteString(")")
	stmts := []string{sb.String()}
	stmts = append(stmts, idxs...)
	return createTableSQL{Statements: stmts}
}

func normalizeType(f fieldTag) string {
	// allow explicit override like varchar(50)
	t := strings.ToLower(f.DBType)
	switch {
	case strings.HasPrefix(t, "varchar"):
		return f.DBType
	case t == "text":
		return "TEXT"
	case t == "timestamptz":
		return "TIMESTAMPTZ"
	case t == "bigint":
		return "BIGINT"
	case t == "integer":
		return "INTEGER"
	case t == "boolean":
		return "BOOLEAN"
	case t == "double precision":
		return "DOUBLE PRECISION"
	case t == "real":
		return "REAL"
	default:
		// fallback
		return f.DBType
	}
}
